export type BusinessGroup = 'PASSIVE' | 'ACTIVE' | 'NETWORK';

export interface BusinessEntry {
  slug: string;
  title: string;
  group: BusinessGroup;
  groupLabel: string;
  update: string;
  released: string;
  releasedIso: string;
  availableFrom: string;
  basePrice: string;
  solo: string;
  cycle: string;
  incomeNote: string;
  summary: string;
  bestFor: string;
  benefits: string[];
  steps: string[];
  image: string;
  imageAlt: string;
  mediaSource: string;
  mapNote: string;
  source: string;
  sourceLabel: string;
}

export const BUSINESS_ENTRIES: BusinessEntry[] = [
  {
    slug: 'acid-lab', title: 'Acid Lab', group: 'PASSIVE', groupLabel: 'Passive production', update: 'Los Santos Drug Wars', released: 'December 13, 2022', releasedIso: '2022-12-13', availableFrom: 'The Freakshop / MTL Brickade 6x6', basePrice: 'GTA$750,000 install; GTA$250,000 equipment upgrade', solo: 'Yes — solo-friendly sell missions', cycle: 'Source supplies → manufacture acid → sell product', incomeNote: 'A fully upgraded full batch has a strong solo sale value; event weeks and public-lobby demand bonuses can change the final total.', summary: 'A mobile production business installed in the Brickade 6x6. It is one of the cleanest solo loops because the lab can be requested in Freemode and its sell missions stay manageable.', bestFor: 'New or solo players building their first reliable income engine.', benefits: ['Complete First Dose and equipment setup to unlock the lab installation', 'Ten Fooligan Jobs unlock the Equipment Upgrade', 'Daily production boost is available from the lab', 'Brickade 6x6 and delivery bike can be requested in Freemode'], steps: ['Complete the First Dose story and steal the Brickade 6x6 equipment.', 'Pay Mutt to install the Acid Lab in the Brickade.', 'Complete 10 Fooligan Jobs, then buy the Equipment Upgrade.', 'Order or steal supplies, boost production when available and sell the finished acid.'], image: '/images/properties/real/acid-lab.jpg', imageAlt: 'Real GTA Online screenshot from the Acid Lab business', mediaSource: 'https://www.gtabase.com/grand-theft-auto-v/properties-gta-online/acid-lab', mapNote: 'The Freakshop is at the north end of Mirror Park Railyard. The mobile lab itself can be requested across Los Santos, so the map is mainly useful for setup and resupply orientation.', source: 'https://www.rockstargames.com/newswire/article/9k72kk9k229481/benefit-from-bonuses-on-acid-lab-sell-and-resupply-missions', sourceLabel: 'Rockstar Acid Lab coverage',
  },
  {
    slug: 'special-cargo', title: 'Special Cargo', group: 'ACTIVE', groupLabel: 'Active sourcing', update: 'Further Adventures in Finance and Felony', released: 'June 7, 2016', releasedIso: '2016-06-07', availableFrom: 'Executive Office + Cargo Warehouse', basePrice: 'GTA$250,000–3,500,000 per warehouse', solo: 'Yes — sales scale with stock size', cycle: 'Buy/source crates → store → sell cargo', incomeNote: 'Revenue scales with warehouse size and stock; double-money event weeks can materially change the return.', summary: 'The classic CEO crate business. Source shipments from the office, stack them in a small, medium or large warehouse, then sell the stock in a timed delivery.', bestFor: 'Active players who like repeatable sourcing and want a business that pairs with CEO work.', benefits: ['Three warehouse sizes support different bankrolls', 'Large warehouses provide the biggest single sale potential', 'Source missions can be run solo or with an organization', 'Cargo can also feed Nightclub warehouse categories'], steps: ['Own an Executive Office and buy a warehouse from the office laptop.', 'Source one, two or three crates per mission based on your risk tolerance.', 'Store stock until you are ready for a timed sale.', 'Sell from the warehouse and use a public-lobby high-demand bonus only when the risk is worth it.'], image: '/images/properties/real/special-cargo-warehouses.jpg', imageAlt: 'Real GTA Online screenshot of a Special Cargo Warehouse', mediaSource: 'https://www.gtabase.com/grand-theft-auto-v/guides/property-types/warehouses', mapNote: 'Warehouse location affects every sourcing and sale drive. Use the Los Santos atlas to choose a compact route network rather than scattering warehouses randomly.', source: 'https://www.gtabase.com/gta-online/property-types/', sourceLabel: 'GTA Online business database via GTA Base',
  },
  {
    slug: 'vehicle-cargo', title: 'Vehicle Cargo', group: 'ACTIVE', groupLabel: 'Active sourcing', update: 'Import/Export', released: 'December 13, 2016', releasedIso: '2016-12-13', availableFrom: 'Executive Office + Vehicle Warehouse', basePrice: 'From GTA$1,500,000', solo: 'Yes — source and export individually', cycle: 'Source vehicle → store → modify → export', incomeNote: 'Top-range exports provide the strongest regular margin, with source and damage costs reducing the gross sale.', summary: 'A focused CEO vehicle loop: steal target cars, store them in a Vehicle Warehouse and export them to buyers for a direct, active payout.', bestFor: 'Players who prefer driving and short active sales over waiting for stock production.', benefits: ['Stores up to 40 sourced vehicles', 'Unlocks Special Vehicle Work', 'High-end exports are the strongest part of the loop', 'Vehicle Warehouse cannot be raided by NPCs or players'], steps: ['Own an Executive Office and buy one Vehicle Warehouse.', 'Source vehicles while keeping the collection balanced for better target rolls.', 'Select a stored car, modify it for the buyer and export it.', 'Avoid damage during the sale because repairs directly cut into the margin.'], image: '/images/properties/real/vehicle-warehouses.jpg', imageAlt: 'Real GTA Online screenshot of a Vehicle Warehouse', mediaSource: 'https://www.gtabase.com/grand-theft-auto-v/guides/property-types/vehicle-warehouses', mapNote: 'A central Vehicle Warehouse shortens source and export missions. Compare the warehouse location against Los Santos Customs and the usual sale districts.', source: 'https://www.gtabase.com/gta-online/properties/', sourceLabel: 'GTA Online properties database via GTA Base',
  },
  {
    slug: 'mc-businesses', title: 'MC Businesses', group: 'PASSIVE', groupLabel: 'Passive production', update: 'Bikers', released: 'October 4, 2016', releasedIso: '2016-10-04', availableFrom: 'MC Clubhouse / Open Road', basePrice: 'GTA$650,000–1,729,000 each', solo: 'Partly — sell volume can require a crew', cycle: 'Buy/steal supplies → produce → defend → sell', incomeNote: 'Cocaine, Meth and Counterfeit Cash are the usual high-priority businesses; production and sale values depend on upgrades and stock.', summary: 'Five production businesses—Cocaine, Meth, Counterfeit Cash, Weed and Document Forgery—run from an MC Clubhouse and can feed a larger Nightclub network.', bestFor: 'Nightclub owners and players ready to manage a multi-business production portfolio.', benefits: ['Own one of each of the five business types', 'Equipment and Staff upgrades improve production', 'Security upgrades reduce raid risk', 'Active businesses unlock Nightclub warehouse categories'], steps: ['Own an MC Clubhouse and buy a business through the Open Road laptop.', 'Complete the setup mission and buy equipment/staff upgrades before scaling stock.', 'Keep supplies moving through purchases or resupply missions.', 'Sell before the stock becomes awkward to move solo, or bring an MC crew for larger sales.'], image: '/images/properties/real/mc-businesses.jpg', imageAlt: 'Real GTA Online screenshot of an MC Meth Lab business', mediaSource: 'https://www.gtabase.com/grand-theft-auto-v/guides/property-types/mc-businesses', mapNote: 'Location changes the distance and difficulty of sales. Compare each business against the city map, especially if you plan to run more than one.', source: 'https://www.gtabase.com/gta-online/property-types/', sourceLabel: 'MC business database via GTA Base',
  },
  {
    slug: 'bunker', title: 'Bunker', group: 'PASSIVE', groupLabel: 'Passive production', update: 'Gunrunning', released: 'June 13, 2017', releasedIso: '2017-06-13', availableFrom: 'Maze Bank Foreclosures', basePrice: 'GTA$1,165,000–2,375,000', solo: 'Yes for controlled stock; crews help with full sales', cycle: 'Supplies → weapons stock/research → sale', incomeNote: 'Stock value depends on product, upgrades and sale destination; research competes with production for staff time.', summary: 'A weapons manufacturing base that combines passive stock production with research for weaponized vehicles and upgrades.', bestFor: 'Players who want a strong feeder business and long-term weapon research.', benefits: ['Produce and sell weapons stock', 'Research weaponized vehicles and Mk II upgrades', 'Unlock Mobile Operations Center support', 'Staff can be split between production and research'], steps: ['Buy a Bunker through Maze Bank Foreclosures.', 'Complete setup and buy Equipment and Staff upgrades before maximizing stock.', 'Choose production or research based on your current goal.', 'Sell controlled stock in one-vehicle batches when playing solo.'], image: '/images/properties/real/bunkers.jpg', imageAlt: 'Real GTA Online screenshot of a Gunrunning Bunker', mediaSource: 'https://www.gtabase.com/grand-theft-auto-v/guides/property-types/bunkers', mapNote: 'Chumash and Farmhouse are popular for practical sale routes. Use the atlas to compare city delivery distance before buying.', source: 'https://www.gtabase.com/gta-online/property-types/', sourceLabel: 'Bunker business guide via GTA Base',
  },
  {
    slug: 'hangar-air-freight', title: 'Hangar Air Freight', group: 'ACTIVE', groupLabel: 'Active sourcing', update: 'Smuggler’s Run', released: 'August 29, 2017', releasedIso: '2017-08-29', availableFrom: 'Maze Bank Foreclosures', basePrice: 'From GTA$1,200,000', solo: 'Yes — sales can be run solo', cycle: 'Source air freight → warehouse → sell cargo', incomeNote: 'Category bonuses and current event multipliers affect the best cargo choice and sale return.', summary: 'An aircraft-centered cargo business where you source and sell Air Freight Cargo, with aircraft storage and optional workshop utility.', bestFor: 'Pilots and players who want an active business tied to their aircraft collection.', benefits: ['Store and customize aircraft', 'Source Air Freight Cargo', 'Fort Zancudo locations offer military-base access', 'Optional workshop and living quarters'], steps: ['Buy a Hangar and select LSIA for city access or Fort Zancudo for military convenience.', 'Source a cargo category repeatedly to build a bonus stack.', 'Store cargo in the hangar and sell when the route is worth the risk.', 'Use the aircraft workshop for the vehicles you actively fly.'], image: '/images/properties/real/hangars.jpg', imageAlt: 'Real GTA Online screenshot of a Smuggler’s Run Hangar', mediaSource: 'https://www.gtabase.com/grand-theft-auto-v/guides/property-types/hangars', mapNote: 'The hangar location determines how often you cross the map. Fort Zancudo favors northern routes; LSIA favors Los Santos and city access.', source: 'https://www.gtabase.com/gta-online/property-types/', sourceLabel: 'Hangar business guide via GTA Base',
  },
  {
    slug: 'nightclub-warehouse', title: 'Nightclub Warehouse', group: 'NETWORK', groupLabel: 'Network hub', update: 'After Hours', released: 'July 24, 2018', releasedIso: '2018-07-24', availableFrom: 'Maze Bank Foreclosures', basePrice: 'GTA$1,080,000–1,700,000', solo: 'Yes — warehouse sales are one delivery loop', cycle: 'Own feeder businesses → assign technicians → sell consolidated stock', incomeNote: 'The warehouse is passive once feeder businesses are owned and technicians assigned; the popularity safe is a separate income stream.', summary: 'The portfolio multiplier. A Nightclub’s technicians quietly accrue goods from businesses you already own, giving you one consolidated sale operation.', bestFor: 'Established players who already own a Bunker, MC businesses, Cargo or Hangar.', benefits: ['Up to five technicians work different product categories', 'Consolidates multiple businesses into one sale', 'Popularity safe provides separate recurring income', 'Terrorbyte can be stored and used from the warehouse'], steps: ['Buy a Nightclub and complete its setup.', 'Own the feeder businesses needed for the product categories you want.', 'Hire technicians and assign them to the most valuable categories.', 'Maintain popularity separately, then sell warehouse stock before the delivery becomes inconvenient.'], image: '/images/properties/real/nightclubs.jpg', imageAlt: 'Real GTA Online screenshot of a Nightclub business', mediaSource: 'https://www.gtabase.com/grand-theft-auto-v/guides/property-types/nightclubs', mapNote: 'Choose a central club location because every consolidated sale starts there. A city site is usually easier to live with than a remote location.', source: 'https://www.rockstargames.com/newswire/article/1748koo9oo3557/Los-Santos-Summer-Special-in-GTA-Online', sourceLabel: 'Rockstar Nightclub coverage',
  },
  {
    slug: 'auto-shop-contracts', title: 'Auto Shop Contracts', group: 'ACTIVE', groupLabel: 'Active missions', update: 'Los Santos Tuners', released: 'July 20, 2021', releasedIso: '2021-07-20', availableFrom: 'Maze Bank Foreclosures', basePrice: 'GTA$1,670,000–1,920,000', solo: 'Yes — Contracts are solo-friendly', cycle: 'Two setups → Contract finale → payout', incomeNote: 'Contract rewards vary by job; the business also earns from customer cars and Exotic Exports.', summary: 'An active vehicle business built around multi-mission Contracts, customer vehicle service and discounted tuning access.', bestFor: 'Solo players who want repeatable mission income without waiting for stock production.', benefits: ['Launch six robbery-style Contracts', 'Service and deliver customer vehicles', 'Unlock discounted vehicle modifications', 'Optional staff, lifts and living quarters'], steps: ['Visit the LS Car Meet and meet Mimi to unlock the purchase route.', 'Buy an Auto Shop and use its Job Board to select a Contract.', 'Complete the two setups, then finish the finale and collect the payout.', 'Add customer service or Exotic Exports between larger Contract runs.'], image: '/images/properties/real/auto-shops.jpg', imageAlt: 'Real GTA Online screenshot of an Auto Shop', mediaSource: 'https://www.gtabase.com/grand-theft-auto-v/guides/property-types/auto-shops', mapNote: 'Auto Shop placement affects Contract setup travel and customer deliveries. A central city site is the safest all-round choice.', source: 'https://www.rockstargames.com/newswire/article/3974k2848172a2/upcoming-improvements-to-the-gta-online-experience', sourceLabel: 'Rockstar Auto Shop coverage',
  },
  {
    slug: 'agency', title: 'Agency', group: 'ACTIVE', groupLabel: 'Active missions', update: 'The Contract', released: 'December 15, 2021', releasedIso: '2021-12-15', availableFrom: 'Dynasty 8 Executive', basePrice: 'GTA$2,010,000–2,830,000', solo: 'Yes — core mission loop is solo-friendly', cycle: 'Security/Payphone work → VIP Contract → safe income', incomeNote: 'The VIP Contract, Security Contracts, Payphone Hits and safe income each use different timers and effort levels.', summary: 'Franklin’s mission headquarters for The Contract, Security Contracts and Payphone Hits, with an optional Armory and Imani Tech workshop.', bestFor: 'Solo players who want varied active work and a reliable mission base.', benefits: ['Launch The Dr. Dre VIP Contract', 'Run Security Contracts and Payphone Hits', 'Optional Vehicle Workshop for Imani Tech', 'Armory adds weapon upgrades and loadout access'], steps: ['Watch the introduction at the LS Golf Club and buy an Agency.', 'Complete the setup missions to unlock Security Contracts and VIP Contract progress.', 'Use Payphone Hits and Security Contracts between larger VIP Contract chapters.', 'Add the Armory and Vehicle Workshop when their utility matches your vehicle plans.'], image: '/images/properties/real/celebrity-solutions-agency.jpg', imageAlt: 'Real GTA Online screenshot of the Celebrity Solutions Agency', mediaSource: 'https://www.gtabase.com/grand-theft-auto-v/guides/property-types/the-agency', mapNote: 'All Agency locations are in Los Santos. A central site reduces travel for Security Contracts and Payphone Hits.', source: 'https://www.rockstargames.com/newswire/article/3974k2848172a2/upcoming-improvements-to-the-gta-online-experience', sourceLabel: 'Rockstar Agency coverage',
  },
  {
    slug: 'salvage-yard', title: 'Salvage Yard', group: 'ACTIVE', groupLabel: 'Active missions', update: 'The Chop Shop', released: 'December 12, 2023', releasedIso: '2023-12-12', availableFrom: 'Maze Bank Foreclosures', basePrice: 'GTA$1,620,000–2,690,000', solo: 'Yes — robberies and towing are solo-friendly', cycle: 'Tow jobs → Salvage Yard Robbery → salvage/sell', incomeNote: 'Rotating robberies and tow jobs have different effort and value; weekly featured targets can change the priority.', summary: 'A vehicle theft and dismantling operation with rotating robberies, towing work and recoverable vehicles.', bestFor: 'Solo players who want a varied vehicle business with short repeatable jobs.', benefits: ['Launch Salvage Yard Robberies', 'Tow vehicles for active income', 'Salvage or sell recovered vehicles', 'Optional staff, storage and lift upgrades'], steps: ['Meet Yusuf Amir and buy a Salvage Yard through Maze Bank Foreclosures.', 'Complete the introduction and use the planning board to select a robbery.', 'Tow vehicles between robberies to keep the yard’s safe income moving.', 'Salvage or sell recovered vehicles and watch for weekly target changes.'], image: '/images/properties/real/salvage-yards.jpg', imageAlt: 'Real GTA Online screenshot of a Salvage Yard', mediaSource: 'https://www.gtabase.com/gta-online/property-types/salvage-yards', mapNote: 'The five Salvage Yard locations cover city and county. Use the atlas to compare robbery travel and tow-job distance.', source: 'https://www.gtabase.com/gta-online/property-types/salvage-yards', sourceLabel: 'Salvage Yard guide via GTA Base',
  },
  {
    slug: 'bail-enforcement', title: 'Bail Enforcement', group: 'ACTIVE', groupLabel: 'Active missions', update: 'Bottom Dollar Bounties', released: 'June 25, 2024', releasedIso: '2024-06-25', availableFrom: 'Maze Bank Foreclosures', basePrice: 'GTA$1,650,000–2,620,000', solo: 'Yes — bounty work is solo-friendly', cycle: 'Find target → capture/eliminate → collect bounty', incomeNote: 'Most Wanted and standard bounty values vary by target; optional agents add a separate passive safe income.', summary: 'A bounty office for Most Wanted targets and regular bounties, with optional agents and an Armory.', bestFor: 'Players who enjoy target pursuit, combat and changing mission locations.', benefits: ['Launch Most Wanted targets', 'Run standard bounty missions', 'Optional agents increase safe income', 'Optional Armory and personal quarters'], steps: ['Buy a Bail Enforcement Office through Maze Bank Foreclosures.', 'Complete the introduction and use the bounty board to select a target.', 'Track, capture or eliminate the target and return for the reward.', 'Add agents if you want the passive safe to work while you do other activities.'], image: '/images/properties/real/bail-enforcement-offices.jpg', imageAlt: 'Real GTA Online screenshot of a Bottom Dollar Bail Enforcement Office', mediaSource: 'https://www.gtabase.com/gta-online/property-types/bottom-dollar-bail-enforcement', mapNote: 'Bounty targets can appear across the full state. A central office reduces the average Los Santos-to-county drive.', source: 'https://www.gtabase.com/gta-online/property-types/bottom-dollar-bail-enforcement', sourceLabel: 'Bail Enforcement guide via GTA Base',
  },
  {
    slug: 'money-fronts', title: 'Money Fronts', group: 'NETWORK', groupLabel: 'Network hub', update: 'Money Fronts', released: 'June 17, 2026', releasedIso: '2026-06-17', availableFrom: 'Money Fronts / Maze Bank Foreclosures', basePrice: 'Varies by front; upgrades extra', solo: 'Yes — front activities are solo-friendly', cycle: 'Run legal front work → manage heat → launder proceeds', incomeNote: 'Front values and bonuses are update-sensitive; heat management is part of keeping the network productive.', summary: 'A laundering network built around the Hands On Car Wash and linked Smoke on the Water and Higgins Helitours fronts.', bestFor: 'Established players who want newer solo-friendly content that connects multiple locations.', benefits: ['Run the Hands On Car Wash front', 'Unlock linked Smoke on the Water and Higgins Helitours fronts', 'Launch Money Laundering missions', 'Use legal activities to manage heat on associated businesses'], steps: ['Complete the Money Fronts introduction and buy the Car Wash.', 'Run front activities to build the network and keep heat under control.', 'Purchase linked fronts once their role fits your existing business portfolio.', 'Rotate legal front work with criminal operations so the network stays productive.'], image: '/images/properties/real/money-fronts-businesses.jpg', imageAlt: 'Real GTA Online screenshot representing the Money Fronts business network', mediaSource: 'https://www.rockstargames.com/gta-online/businesses/money-fronts', mapNote: 'The front locations are spread across Los Santos. Use the atlas to plan a repeatable Car Wash, Smoke on the Water and Higgins Helitours loop.', source: 'https://www.rockstargames.com/gta-online/businesses/money-fronts', sourceLabel: 'Rockstar Money Fronts page',
  },
  {
    slug: 'fif-files', title: 'FIB Files', group: 'ACTIVE', groupLabel: 'Active missions', update: 'A Safehouse in the Hills', released: 'December 10, 2025', releasedIso: '2025-12-10', availableFrom: 'Darnell Bros Garment Factory', basePrice: 'GTA$2,350,000', solo: 'Yes — mission base is solo-friendly', cycle: 'Prep board → FIB File setup → finale', incomeNote: 'Mission rewards vary by file and current bonuses; the value is in repeatable structured operations rather than passive stock.', summary: 'The mission operation attached to Darnell Bros Garment Factory, built around repeatable FIB Files and infiltration prep.', bestFor: 'Solo players who prefer structured operations to delivery-heavy businesses.', benefits: ['Launch FIB Files', 'Use a dedicated planning board and specialist preps', 'New mission base and spawn location', 'Fits naturally into a rotation with other active businesses'], steps: ['Complete the A Safehouse in the Hills introduction.', 'Buy Darnell Bros Garment Factory through Maze Bank Foreclosures.', 'Select an FIB File and complete its required prep work.', 'Run the finale, then rotate to another file or business while it refreshes.'], image: '/images/properties/real/darnell-bros-garment-factory.jpg', imageAlt: 'Real GTA Online screenshot of the Darnell Bros Garment Factory', mediaSource: 'https://www.gtabase.com/properties/gta-online/darnell-bros-garment-factory', mapNote: 'The factory operates from Los Santos. Use the city atlas to plan the approach from your main safehouse and the file locations.', source: 'https://www.gtabase.com/properties/gta-online/darnell-bros-garment-factory', sourceLabel: 'Darnell Bros guide via GTA Base',
  },
];

export const BUSINESS_GROUPS: { key: 'ALL' | BusinessGroup; label: string; count: number }[] = [
  { key: 'ALL', label: `All businesses · ${BUSINESS_ENTRIES.length}`, count: BUSINESS_ENTRIES.length },
  { key: 'PASSIVE', label: 'Passive production', count: BUSINESS_ENTRIES.filter((business) => business.group === 'PASSIVE').length },
  { key: 'ACTIVE', label: 'Active missions', count: BUSINESS_ENTRIES.filter((business) => business.group === 'ACTIVE').length },
  { key: 'NETWORK', label: 'Network hubs', count: BUSINESS_ENTRIES.filter((business) => business.group === 'NETWORK').length },
];
