export type HeistGroup = 'CLASSIC' | 'DOOMSDAY' | 'MODERN';

export interface HeistRoute {
  name: string;
  detail: string;
}

export interface HeistEntry {
  slug: string;
  title: string;
  group: HeistGroup;
  groupLabel: string;
  update: string;
  released: string;
  releasedIso: string;
  players: string;
  host: string;
  setup: string;
  payout: string;
  cooldown: string;
  solo: string;
  summary: string;
  bestFor: string;
  steps: string[];
  image: string;
  imageAlt: string;
  mediaSource: string;
  mediaSourceLabel: string;
  mapImage: string;
  mapAlt: string;
  mapNote: string;
  mapSource: string;
  mapSourceLabel: string;
  routes: HeistRoute[];
  requirements: string[];
  source: string;
  sourceLabel: string;
}

export const HEIST_ENTRIES: HeistEntry[] = [
  {
    slug: 'fleeca-job',
    title: 'The Fleeca Job',
    group: 'CLASSIC',
    groupLabel: 'Classic heist',
    update: 'Heists',
    released: 'March 10, 2015',
    releasedIso: '2015-03-10',
    players: '2 players',
    host: 'High-End Apartment',
    setup: 'GTA$11,500',
    payout: 'GTA$201,250 normal / GTA$251,563 hard repeat; first weekly run up to GTA$377,344',
    cooldown: '48 minutes with a crew',
    solo: 'No — finale requires 2',
    summary: 'A compact bank robbery that teaches the original heist loop: scope, prep, drill the vault and survive the getaway.',
    bestFor: 'First-time crews and quick two-player runs.',
    steps: ['Host the score from your apartment and complete the Fleeca scope-out.', 'Steal the Kuruma and complete the planning prep, then bring your second player to the finale.', 'Hack the vault, drill the boxes and collect the take before the alarm closes the bank down.', 'Use the armored Kuruma for the escape and deliver the car to Lester’s buyer without losing the cash.'],
    image: '/images/heists/real/fleeca-job.jpg',
    imageAlt: 'Real GTA Online screenshot showing The Fleeca Job',
    mediaSource: 'https://www.gtabase.com/gta-online/jobs/heists/the-fleeca-job',
    mediaSourceLabel: 'Real screenshot via GTA Base',
    mapImage: '/images/heists/real/los-santos-atlas.jpg',
    mapAlt: 'Real GTA 5 atlas map showing Los Santos and Blaine County',
    mapNote: 'Use the city atlas to orient the Fleeca branch, apartment start and the northbound escape roads before launching.',
    mapSource: 'https://www.gtabase.com/grand-theft-auto-v/map-locations/',
    mapSourceLabel: 'Los Santos atlas via GTA Base',
    routes: [
      { name: 'Clean two-player split', detail: 'One player handles the vault hack while the other drills, then both regroup for the armored-car getaway.' },
      { name: 'Fast getaway', detail: 'Keep the escape clean, avoid unnecessary street damage and protect the car so the final take is not reduced.' },
    ],
    requirements: ['Rank 12 or higher to host', 'High-End Apartment with a planning room', 'Pay the host setup fee', 'One additional crew member'],
    source: 'https://www.rockstargames.com/newswire/article/ak14o8838472ka/gtav-updates-online-heists-coming-march-10',
    sourceLabel: 'Rockstar launch announcement',
  },
  {
    slug: 'prison-break',
    title: 'The Prison Break',
    group: 'CLASSIC',
    groupLabel: 'Classic heist',
    update: 'Heists',
    released: 'March 10, 2015',
    releasedIso: '2015-03-10',
    players: '4 players',
    host: 'High-End Apartment',
    setup: 'GTA$25,000',
    payout: 'GTA$700,000 normal / GTA$875,000 hard repeat; first weekly run up to GTA$1,312,500',
    cooldown: '48 minutes with a crew',
    solo: 'No — finale requires 4',
    summary: 'Break Rashkovsky out of Bolingbroke Penitentiary, coordinate four specialist roles and keep the extraction target alive.',
    bestFor: 'Crews that enjoy role-based coordination.',
    steps: ['Host the heist from a high-end apartment and complete the four prison-break setups.', 'Assign inmate, prison officer, demolition and pilot roles before starting the finale.', 'Enter Bolingbroke, free Rashkovsky and keep him moving while the team clears the prison route.', 'Fly the Velum to the extraction point, land safely and deliver Rashkovsky to the drop-off.'],
    image: '/images/heists/real/prison-break.jpg',
    imageAlt: 'Real GTA Online screenshot showing The Prison Break',
    mediaSource: 'https://www.gtabase.com/gta-online/jobs/heists/the-prison-break',
    mediaSourceLabel: 'Real screenshot via GTA Base',
    mapImage: '/images/heists/real/los-santos-atlas.jpg',
    mapAlt: 'Real GTA 5 atlas map showing Bolingbroke Penitentiary and the city',
    mapNote: 'Bolingbroke is north of Los Santos. Plan the prison approach and the Velum extraction route before the timer starts.',
    mapSource: 'https://www.gtabase.com/grand-theft-auto-v/map-locations/',
    mapSourceLabel: 'Los Santos atlas via GTA Base',
    routes: [
      { name: 'Balanced prison team', detail: 'Use an inmate and officer inside, a demolition player outside and a pilot ready for a controlled extraction.' },
      { name: 'Extraction discipline', detail: 'Keep Rashkovsky clear of crossfire, land cleanly and prioritize the escape timer over extra kills.' },
    ],
    requirements: ['Rank 12 or higher to host', 'High-End Apartment with a planning room', 'Pay the host setup fee', 'Three additional crew members'],
    source: 'https://www.rockstargames.com/newswire/article/ak14o8838472ka/gtav-updates-online-heists-coming-march-10',
    sourceLabel: 'Rockstar launch announcement',
  },
  {
    slug: 'humane-labs-raid',
    title: 'The Humane Labs Raid',
    group: 'CLASSIC',
    groupLabel: 'Classic heist',
    update: 'Heists',
    released: 'March 10, 2015',
    releasedIso: '2015-03-10',
    players: '4 players',
    host: 'High-End Apartment',
    setup: 'GTA$25,000',
    payout: 'GTA$945,000 normal / GTA$1,181,250 hard repeat; first weekly run up to GTA$1,771,875',
    cooldown: '48 minutes with a crew',
    solo: 'No — finale requires 4',
    summary: 'Raid a secret government laboratory after stealing an EMP, then execute a night-time infiltration and escape by air.',
    bestFor: 'Teams that can handle stealth, night vision and a demanding finale.',
    steps: ['Complete the Humane Labs prep chain, including the EMP delivery and Valkyrie preparation.', 'Place the EMP at Humane Labs, then return later with night vision and the correct stealth loadout.', 'Infiltrate the lab, secure the objective and keep the team together through the alarm transition.', 'Reach the beach, board the Valkyrie and protect the helicopter during the extraction.'],
    image: '/images/heists/real/humane-labs-raid.jpg',
    imageAlt: 'Real GTA Online screenshot showing The Humane Labs Raid',
    mediaSource: 'https://www.gtabase.com/gta-online/jobs/heists/the-humane-labs-raid',
    mediaSourceLabel: 'Real screenshot via GTA Base',
    mapImage: '/images/heists/real/los-santos-atlas.jpg',
    mapAlt: 'Real GTA 5 atlas map showing Humane Labs and the eastern coastline',
    mapNote: 'Humane Labs sits on the east coast. Keep the lab approach, beach extraction and air route in the same mental plan.',
    mapSource: 'https://www.gtabase.com/grand-theft-auto-v/map-locations/',
    mapSourceLabel: 'Los Santos atlas via GTA Base',
    routes: [
      { name: 'EMP stealth', detail: 'Deliver the EMP to the lab, enter quietly and avoid breaking stealth until the team reaches the objective.' },
      { name: 'Heavy extraction', detail: 'If the alarm goes up, regroup quickly, secure the beach and protect the Valkyrie rather than splitting the team.' },
    ],
    requirements: ['Rank 12 or higher to host', 'High-End Apartment with a planning room', 'Pay the host setup fee', 'Three additional crew members'],
    source: 'https://www.rockstargames.com/newswire/article/ak14o8838472ka/gtav-updates-online-heists-coming-march-10',
    sourceLabel: 'Rockstar launch announcement',
  },
  {
    slug: 'series-a-funding',
    title: 'Series A Funding',
    group: 'CLASSIC',
    groupLabel: 'Classic heist',
    update: 'Heists',
    released: 'March 10, 2015',
    releasedIso: '2015-03-10',
    players: '4 players',
    host: 'High-End Apartment',
    setup: 'GTA$25,000',
    payout: 'GTA$707,000 normal / GTA$883,750 hard repeat; first weekly run up to GTA$1,325,625',
    cooldown: '48 minutes with a crew',
    solo: 'No — finale requires 4',
    summary: 'Trevor’s supply-chain score moves coke, weed, meth and stolen product before a full-scale warehouse finale.',
    bestFor: 'Action-focused crews that prefer combat over puzzles.',
    steps: ['Host from your apartment and complete the product-specific setups for coke, weed, meth and stolen supplies.', 'Assign drivers and gunners so every convoy has a clear owner and backup.', 'Move the product to the warehouse while watching vehicle health and enemy spawns.', 'Defend the warehouse and escort the final shipment to Trevor’s drop-off.'],
    image: '/images/heists/real/series-a-funding.jpg',
    imageAlt: 'Real GTA Online screenshot showing Series A Funding',
    mediaSource: 'https://www.gtabase.com/gta-online/jobs/heists/series-a-funding',
    mediaSourceLabel: 'Real screenshot via GTA Base',
    mapImage: '/images/heists/real/los-santos-atlas.jpg',
    mapAlt: 'Real GTA 5 atlas map showing the city and Blaine County supply routes',
    mapNote: 'Series A moves across city and county roads. Use the atlas to pre-plan the warehouse side of the convoy instead of improvising turns.',
    mapSource: 'https://www.gtabase.com/grand-theft-auto-v/map-locations/',
    mapSourceLabel: 'Los Santos atlas via GTA Base',
    routes: [
      { name: 'Prep-by-prep control', detail: 'Assign each supply run to a player who knows the route, then stage vehicles and weapons before the warehouse finale.' },
      { name: 'Aggressive push', detail: 'Keep the convoy moving, clear blockers quickly and protect the product instead of chasing every enemy.' },
    ],
    requirements: ['Rank 12 or higher to host', 'High-End Apartment with a planning room', 'Pay the host setup fee', 'Three additional crew members'],
    source: 'https://www.rockstargames.com/newswire/article/ak14o8838472ka/gtav-updates-online-heists-coming-march-10',
    sourceLabel: 'Rockstar launch announcement',
  },
  {
    slug: 'pacific-standard-job',
    title: 'The Pacific Standard Job',
    group: 'CLASSIC',
    groupLabel: 'Classic heist',
    update: 'Heists',
    released: 'March 10, 2015',
    releasedIso: '2015-03-10',
    players: '4 players',
    host: 'High-End Apartment',
    setup: 'GTA$25,000',
    payout: 'Up to GTA$1,500,000 normal / GTA$1,875,000 hard repeat; first weekly run up to GTA$2,812,500',
    cooldown: '48 minutes with a crew',
    solo: 'No — finale requires 4',
    summary: 'Hit the biggest bank in the original lineup, then carry the take through a pursuit where damage directly eats into the cash.',
    bestFor: 'Experienced four-player crews chasing a classic finale.',
    steps: ['Complete the Pacific Standard setup chain and bring a four-player team with reliable combat and driving roles.', 'Scope the bank and acquire the getaway bikes, convoy vehicles and hacking equipment.', 'Clear the bank, control the hostages and let the designated cash carrier stay protected.', 'Escape through the alley route, avoid bike crashes and reach the canyon parachute drop without shredding the take.'],
    image: '/images/heists/real/pacific-standard-job.jpg',
    imageAlt: 'Real GTA Online screenshot showing The Pacific Standard Job',
    mediaSource: 'https://www.gtabase.com/gta-online/jobs/heists/the-pacific-standard-job',
    mediaSourceLabel: 'Real screenshot via GTA Base',
    mapImage: '/images/heists/real/los-santos-atlas.jpg',
    mapAlt: 'Real GTA 5 atlas map showing Downtown Los Santos and the Pacific Standard route',
    mapNote: 'The finale starts in Downtown and ends outside the city. Use the atlas to memorize the bank-to-canyon escape before carrying cash.',
    mapSource: 'https://www.gtabase.com/grand-theft-auto-v/map-locations/',
    mapSourceLabel: 'Los Santos atlas via GTA Base',
    routes: [
      { name: 'Single cash carrier', detail: 'Let one player carry most of the take while the others form a protective screen to limit bag damage.' },
      { name: 'Armored getaway', detail: 'Use a reliable armored vehicle for the escape, avoid steep shortcuts and do not trade gunfire for unnecessary speed.' },
    ],
    requirements: ['Rank 12 or higher to host', 'High-End Apartment with a planning room', 'Pay the host setup fee', 'Three additional crew members'],
    source: 'https://www.rockstargames.com/newswire/article/ak14o8838472ka/gtav-updates-online-heists-coming-march-10',
    sourceLabel: 'Rockstar launch announcement',
  },
  {
    slug: 'data-breaches',
    title: 'Act I — The Data Breaches',
    group: 'DOOMSDAY',
    groupLabel: 'Doomsday act',
    update: 'The Doomsday Heist',
    released: 'December 12, 2017',
    releasedIso: '2017-12-12',
    players: '2–4 players',
    host: 'Facility',
    setup: 'GTA$65,000',
    payout: 'GTA$877,500 normal / GTA$1,096,875 hard repeat; first weekly run up to GTA$1,340,381',
    cooldown: '48 minutes with a crew',
    solo: 'No — finale requires at least 2',
    summary: 'Take on Avon and the IAA in the opening Doomsday act, moving from stolen tech and data recovery into a high-security finale.',
    bestFor: 'Two-player teams that want a shorter tactical heist.',
    steps: ['Own a Facility, register as a VIP, CEO or MC President and complete Act I’s freemode prep missions.', 'Finish the locked setup missions, bringing armor and a weapon loadout for close-quarters fights.', 'Recover the data and breach the facility while one player focuses on the objective and the other clears threats.', 'Secure the servers, survive the extraction and deliver the recovered intelligence to finish the act.'],
    image: '/images/heists/real/doomsday-data-breaches.jpg',
    imageAlt: 'Real GTA Online screenshot from The Doomsday Heist: The Data Breaches',
    mediaSource: 'https://www.gtabase.com/gta-online/jobs/heists/the-doomsday-heist-act-1-the-data-breaches',
    mediaSourceLabel: 'Real screenshot via GTA Base',
    mapImage: '/images/heists/real/los-santos-atlas.jpg',
    mapAlt: 'Real GTA 5 atlas map showing Los Santos locations used by Doomsday Act I',
    mapNote: 'Act I jumps between Los Santos and the Facility. Use the atlas for the long freemode prep drives, then rely on cover indoors.',
    mapSource: 'https://www.gtabase.com/grand-theft-auto-v/map-locations/',
    mapSourceLabel: 'Los Santos atlas via GTA Base',
    routes: [
      { name: 'Ground-and-tech', detail: 'Finish the freemode preps, bring reliable armor and keep one player focused on the objective while the other clears threats.' },
      { name: 'Fast finale', detail: 'Use a disciplined loadout, push between cover and do not let the server-room fight turn into a long attrition battle.' },
    ],
    requirements: ['Own a Facility to host', 'Be a VIP, CEO or MC President', 'Pay the act setup cost', 'One to three additional crew members'],
    source: 'https://www.rockstargames.com/newswire/article/ak14o88389ooo3/GTA-Online-The-Doomsday-Heist-Out-Now',
    sourceLabel: 'Rockstar launch announcement',
  },
  {
    slug: 'bogdan-problem',
    title: 'Act II — The Bogdan Problem',
    group: 'DOOMSDAY',
    groupLabel: 'Doomsday act',
    update: 'The Doomsday Heist',
    released: 'December 12, 2017',
    releasedIso: '2017-12-12',
    players: '2–4 players',
    host: 'Facility',
    setup: 'GTA$95,000',
    payout: 'GTA$1,282,500 normal / GTA$1,603,125 hard repeat; first weekly run up to GTA$1,959,019',
    cooldown: '48 minutes with a crew',
    solo: 'No — finale requires at least 2',
    summary: 'Split the crew between an underwater rescue and an airborne control-room assault while a rogue submarine threatens Los Santos.',
    bestFor: 'Two-player crews comfortable dividing objectives.',
    steps: ['Complete Act II’s prep missions from the Facility and finish the required setup missions.', 'Split roles between the Avenger team and the underwater submarine team before entering the finale.', 'Board the submarine, rescue Agent ULP and clear the control room while the air team manages the exterior pressure.', 'Regroup at the Avenger, lose the pursuit and deliver the team to complete the act.'],
    image: '/images/heists/real/doomsday-bogdan-problem.jpg',
    imageAlt: 'Real GTA Online screenshot from The Doomsday Heist: The Bogdan Problem',
    mediaSource: 'https://www.gtabase.com/gta-online/jobs/heists/the-doomsday-heist-act-2-the-bogdan-problem',
    mediaSourceLabel: 'Real screenshot via GTA Base',
    mapImage: '/images/heists/real/los-santos-atlas.jpg',
    mapAlt: 'Real GTA 5 atlas map showing the city, coast and submarine operation area',
    mapNote: 'Act II alternates between city operations and the coastline. Confirm the submarine and Avenger rendezvous points before launch.',
    mapSource: 'https://www.gtabase.com/grand-theft-auto-v/map-locations/',
    mapSourceLabel: 'Los Santos atlas via GTA Base',
    routes: [
      { name: 'Submarine + air split', detail: 'Send the strongest pilot to the Avenger and the strongest close-quarters player underwater; communicate every handoff.' },
      { name: 'Controlled boarding', detail: 'Clear the submarine room by room, keep the rescue target moving and use the finale timer as your pacing guide.' },
    ],
    requirements: ['Own a Facility to host', 'Be a VIP, CEO or MC President', 'Pay the act setup cost', 'One to three additional crew members'],
    source: 'https://www.rockstargames.com/newswire/article/ak14o88389ooo3/GTA-Online-The-Doomsday-Heist-Out-Now',
    sourceLabel: 'Rockstar launch announcement',
  },
  {
    slug: 'doomsday-scenario',
    title: 'Act III — The Doomsday Scenario',
    group: 'DOOMSDAY',
    groupLabel: 'Doomsday act',
    update: 'The Doomsday Heist',
    released: 'December 12, 2017',
    releasedIso: '2017-12-12',
    players: '2–4 players',
    host: 'Facility',
    setup: 'GTA$120,000',
    payout: 'GTA$1,620,000 normal / GTA$2,025,000 hard repeat; first weekly run up to GTA$2,474,550',
    cooldown: '48 minutes with a crew',
    solo: 'No — finale requires at least 2',
    summary: 'The finale of the Doomsday arc: breach the mountain facility, stop the launch sequence and shut down Avon’s plan.',
    bestFor: 'Veteran crews who want the hardest classic-style finale.',
    steps: ['Complete the Act III freemode preps and all required setups from the Facility planning screen.', 'Bring armor, explosives and a full team with one player assigned to objective interactions.', 'Fight through the missile facility, rescue the agents and stop the launch sequence.', 'Finish the final confrontation, escape the base and deliver the survivors to close the Doomsday story.'],
    image: '/images/heists/real/doomsday-scenario.jpg',
    imageAlt: 'Real GTA Online screenshot from The Doomsday Heist: The Doomsday Scenario',
    mediaSource: 'https://www.gtabase.com/gta-online/jobs/heists/the-doomsday-heist-act-3-the-doomsday-scenario',
    mediaSourceLabel: 'Real screenshot via GTA Base',
    mapImage: '/images/heists/real/los-santos-atlas.jpg',
    mapAlt: 'Real GTA 5 atlas map showing the Blaine County mountain region',
    mapNote: 'Act III uses the northern mountain region and hidden facility approaches. Plan the long drive north and keep a heavy vehicle ready.',
    mapSource: 'https://www.gtabase.com/grand-theft-auto-v/map-locations/',
    mapSourceLabel: 'Los Santos atlas via GTA Base',
    routes: [
      { name: 'Stealth-first breach', detail: 'Use cover and suppressed weapons to reduce pressure before the facility fight becomes a full assault.' },
      { name: 'Heavy assault', detail: 'Bring armor, explosives and a clear formation; split only when the objective forces the team to do so.' },
    ],
    requirements: ['Own a Facility to host', 'Be a VIP, CEO or MC President', 'Pay the act setup cost', 'One to three additional crew members'],
    source: 'https://www.rockstargames.com/newswire/article/ak14o88389ooo3/GTA-Online-The-Doomsday-Heist-Out-Now',
    sourceLabel: 'Rockstar launch announcement',
  },
  {
    slug: 'diamond-casino-heist',
    title: 'The Diamond Casino Heist',
    group: 'MODERN',
    groupLabel: 'Modern heist',
    update: 'The Diamond Casino Heist',
    released: 'December 12, 2019',
    releasedIso: '2019-12-12',
    players: '2–4 players',
    host: 'Arcade',
    setup: 'GTA$25,000',
    payout: 'About GTA$1.48M–2.33M repeat by vault target; first weekly run can reach about GTA$4.71M with diamonds before cuts',
    cooldown: '48 minutes with a crew',
    solo: 'No — finale requires at least 2',
    summary: 'Scope the casino, choose a crew and crack the vault using one of three distinct approaches with target loot that changes between runs.',
    bestFor: 'Coordinated duos and crews that like replayable planning choices.',
    steps: ['Own an Arcade, complete the casino scope-out and photograph the vault contents and access points.', 'Choose Big Con, Silent & Sneaky or Aggressive, then buy the approach-specific prep work you actually need.', 'Enter through the selected access point, reach the vault and maximize the timer while collecting the target loot.', 'Escape through the cleanest route, lose the cops and reach the buyer without letting damage or guards erase the take.'],
    image: '/images/heists/real/diamond-casino-heist.jpg',
    imageAlt: 'Real GTA Online screenshot showing The Diamond Casino Heist',
    mediaSource: 'https://www.gtabase.com/gta-online/jobs/heists/the-diamond-casino-heist',
    mediaSourceLabel: 'Real screenshot via GTA Base',
    mapImage: '/images/heists/real/los-santos-atlas.jpg',
    mapAlt: 'Real GTA 5 atlas map showing Vinewood and the Diamond Casino area',
    mapNote: 'The Casino sits in Vinewood. Use the city atlas to learn the Arcade-to-Casino approach and the northbound escape options.',
    mapSource: 'https://www.gtabase.com/grand-theft-auto-v/map-locations/',
    mapSourceLabel: 'Los Santos atlas via GTA Base',
    routes: [
      { name: 'The Big Con', detail: 'Use a disguise route to reach the vault with less resistance, then switch to a fast exit when the cover breaks.' },
      { name: 'Silent & Sneaky', detail: 'Stay off cameras, use suppressed weapons and take the cleanest path through the vault floor.' },
      { name: 'Aggressive', detail: 'Bring armor and explosives, accept the louder escape and focus on collecting the target before the timer collapses.' },
    ],
    requirements: ['Own an Arcade to host', 'Complete the casino scope-out', 'Pay the host setup fee', 'At least one additional crew member'],
    source: 'https://www.rockstargames.com/newswire/article/51974aa3a85959/The-Diamond-Casino-Heist-Now-Available',
    sourceLabel: 'Rockstar launch announcement',
  },
  {
    slug: 'cayo-perico-heist',
    title: 'The Cayo Perico Heist',
    group: 'MODERN',
    groupLabel: 'Modern heist',
    update: 'The Cayo Perico Heist',
    released: 'December 15, 2020',
    releasedIso: '2020-12-15',
    players: '1–4 players',
    host: 'Kosatka submarine',
    setup: 'GTA$100,000',
    payout: 'GTA$400,000–910,000 primary target value, plus secondary loot; Elite adds GTA$50,000 or GTA$100,000',
    cooldown: '144 minutes solo / 48 minutes with a crew',
    solo: 'Yes — the only full heist playable solo',
    summary: 'Scout El Rubio’s island, pick your entry and escape points, then leave with a primary target and as much bag-filling secondary loot as your team can carry.',
    bestFor: 'Solo grinders, stealth players and flexible small crews.',
    steps: ['Meet Miguel at The Music Locker, buy the Kosatka and launch Gather Intel from the planning table.', 'Scout the compound, drainage tunnel, docks, airstrip and secondary loot, then choose a quiet entry and exit.', 'Complete the mandatory approach, equipment and weapon preps; buy the cutting torch when using the drainage tunnel.', 'Infiltrate, steal the primary target, fill the bag with the best nearby secondary loot and swim or drive to the escape point.'],
    image: '/images/heists/real/cayo-perico-heist.jpg',
    imageAlt: 'Real GTA Online screenshot showing The Cayo Perico Heist',
    mediaSource: 'https://www.gtabase.com/gta-online/jobs/heists/the-cayo-perico-heist',
    mediaSourceLabel: 'Real screenshot via GTA Base',
    mapImage: '/images/heists/real/cayo-perico-atlas.jpg',
    mapAlt: 'Real Cayo Perico atlas map showing the compound, airstrip, docks and island roads',
    mapNote: 'This is the island map to use during Gather Intel. Mark the compound entry, drainage tunnel, best secondary loot and your escape waterline.',
    mapSource: 'https://www.gtabase.com/grand-theft-auto-v/map-locations/',
    mapSourceLabel: 'Cayo Perico atlas via GTA Base',
    routes: [
      { name: 'Kosatka drainage tunnel', detail: 'Use the submarine approach and cutting torch to enter directly beneath the compound, then leave by the sea.' },
      { name: 'Longfin dock sweep', detail: 'Arrive at a dock, fill the bag with the best nearby secondary loot and reach the compound by boat.' },
      { name: 'Crew value run', detail: 'Bring a second player to unlock compound gold and use the extra bag space to beat the solo ceiling.' },
    ],
    requirements: ['Meet Miguel Madrazo at The Music Locker', 'Own a Kosatka to host', 'Complete Gather Intel and repeatable preps', 'Pay the setup fee each run'],
    source: 'https://www.rockstargames.com/newswire/article/89k8a554557145/the-cayo-perico-heist-coming-december-15-to-gta-online',
    sourceLabel: 'Rockstar launch announcement',
  },
  {
    slug: 'kortz-center-heist',
    title: 'The Kortz Center Heist',
    group: 'MODERN',
    groupLabel: 'Modern heist',
    update: 'The Kortz Center Heist',
    released: 'July 14, 2026',
    releasedIso: '2026-07-14',
    players: '1–4 players',
    host: 'Mansion with Art Studio',
    setup: 'GTA$0 after weekly reset; GTA$100,000 for additional setups',
    payout: 'First weekly primary sale can reach GTA$1,925,000 plus secondary loot; repeat primary examples are about GTA$308,000–481,250',
    cooldown: 'Weekly reset controls the boosted sale; repeats use buyer-fatigue values',
    solo: 'Yes — team play opens more secondary loot rooms and carries more bags',
    summary: 'Scope Los Santos’ cultural landmark, forge an exit plan and steal rotating paintings from the Bell Building before security closes in.',
    bestFor: 'Players who want a weekly high-value run and crews that can carry more art.',
    steps: ['Own a Mansion and buy the Art Studio expansion, then scope the Kortz Center from the planning table.', 'Complete the chosen approach and prep missions, including replicas, loadout and the buyer-request list when available.', 'Enter the Bell Building, reach the basement, disable the lasers and hack the vault keypad.', 'Steal the primary artwork, wipe the footage, leave through the selected exit and deliver the paintings to the lockup.'],
    image: '/images/heists/real/kortz-center-heist.jpg',
    imageAlt: 'Real GTA Online screenshot showing The Kortz Center Heist',
    mediaSource: 'https://www.gtabase.com/missions/gta-online/heists/the-kortz-center-heist',
    mediaSourceLabel: 'Real screenshot via GTA Base',
    mapImage: '/images/heists/real/los-santos-atlas.jpg',
    mapAlt: 'Real GTA 5 atlas map showing Pacific Bluffs and the Kortz Center area',
    mapNote: 'The Kortz Center is in Pacific Bluffs on the west side of Los Santos. Use the atlas to plan the Mansion-to-museum approach and clean exit.',
    mapSource: 'https://www.gtabase.com/grand-theft-auto-v/map-locations/',
    mapSourceLabel: 'Los Santos atlas via GTA Base',
    routes: [
      { name: 'Staff entrance', detail: 'Use a low-profile entry, keep the early floors controlled and leave through the route that matches your scoped exit.' },
      { name: 'Loading bay', detail: 'A practical solo-friendly route: get inside quickly, prioritize the primary target and protect the escape vehicle.' },
      { name: 'Skylight or sewer', detail: 'Use optional scope information and prep work to trade speed for a safer, more controlled vault approach.' },
    ],
    requirements: ['Own a Mansion', 'Buy the GTA$4,700,000 Art Studio expansion to host', 'Scope the Kortz Center', 'Pay the repeat planning fee when applicable'],
    source: 'https://www.rockstargames.com/newswire/article/2525o93834o413/the-kortz-center-heist-now-available-in-gta-online',
    sourceLabel: 'Rockstar launch announcement',
  },
];

export const HEIST_GROUPS: { key: 'ALL' | HeistGroup; label: string; count: number }[] = [
  { key: 'ALL', label: 'All heists', count: HEIST_ENTRIES.length },
  { key: 'CLASSIC', label: 'Classic · 5', count: 5 },
  { key: 'DOOMSDAY', label: 'Doomsday · 3', count: 3 },
  { key: 'MODERN', label: 'Modern · 3', count: 3 },
];
