export const hubs: Record<string,{title:string;description:string;game?:string;kind?:string;category?:string;verification?:string}>={
  'guides':{title:'Know the city. Own your session.',description:'Practical GTA guides with sourced information and clear verification dates.',kind:'GUIDE'},
  'rumors':{title:'The rumor desk.',description:'Community speculation and unconfirmed reports. None of these stories should be treated as official announcements.',verification:'RUMOR'},
  'gta-online/heists':{title:'Plan your next score.',description:'Heist requirements, approaches and sourced gameplay details. No invented payouts.',game:'GTA_ONLINE',kind:'HEIST'},
  'gta-online/properties':{title:'Build a portfolio that pays back.',description:'Property costs, locations, unlocks and buying priorities across GTA Online.',game:'GTA_ONLINE'},
  'gta-online/businesses':{title:'Build your Los Santos empire.',description:'Business guides and related GTA Online news.',game:'GTA_ONLINE',category:'BUSINESSES'},
  'gta-online/events':{title:'What’s happening in Los Santos.',description:'Sourced events, announcements and limited-time content.',game:'GTA_ONLINE',category:'EVENTS'},
  'gta-online/gta-plus':{title:'Your GTA+ briefing.',description:'Membership benefits and announcements, with dates and sources.',game:'GTA_ONLINE',category:'GTA_PLUS'},
  'gta-online/missions':{title:'Your next mission starts here.',description:'Mission news and guides for GTA Online.',game:'GTA_ONLINE',category:'MISSIONS'},
  'gta-online/updates':{title:'Every update, on the wire.',description:'New GTA Online content and official announcements.',game:'GTA_ONLINE',category:'UPDATE'},
  'gta-online/beginner-guides':{title:'Your first steps in Los Santos.',description:'Beginner guides and verified advice to get you started.',game:'GTA_ONLINE',kind:'GUIDE'},
  'gta-6/news':{title:'The latest from GTA VI.',description:'Sourced reporting on the next Grand Theft Auto.',game:'GTA_6'},
  'gta-6/official-announcements':{title:'Straight from the source.',description:'Officially confirmed GTA VI announcements.',game:'GTA_6',verification:'CONFIRMED'},
  'gta-6/characters':{title:'The people of GTA VI.',description:'Character profiles built from official descriptions and appearances.',game:'GTA_6',kind:'CHARACTER'},
  'gta-6/locations':{title:'Explore the world of GTA VI.',description:'Locations, official details and related announcements.',game:'GTA_6',kind:'LOCATION'},
  'gta-6/trailers':{title:'Every trailer. Every detail.',description:'Official GTA VI trailers and clearly sourced analysis.',game:'GTA_6',kind:'TRAILER'},
  'gta-6/vehicles':{title:'The rides of GTA VI.',description:'Vehicles and details identified in official GTA VI material.',game:'GTA_6',category:'VEHICLES'},
  'gta-6/screenshots':{title:'GTA VI through the lens.',description:'Official media announcements link directly to the source. Publisher images are not rehosted without permission.',game:'GTA_6',category:'MEDIA'},
  'gta-6/features':{title:'The details that matter.',description:'Sourced features and carefully classified GTA VI reporting.',game:'GTA_6',kind:'FEATURE'},
  'gta-6/everything-we-know':{title:'Everything we can verify.',description:'The GTA VI knowledge base. Official facts, with sources attached.',game:'GTA_6',verification:'CONFIRMED'},
  'gta-6/rumors':{title:'GTA VI: the rumor desk.',description:'Unconfirmed community speculation. Rumors are never official facts.',game:'GTA_6',verification:'RUMOR'},
  'gta-6/timeline':{title:'The road to GTA VI.',description:'Published announcements and reporting, with their original dates.',game:'GTA_6'},
  'gta-6/release-date':{title:'GTA VI release information.',description:'The configured, officially sourced release date and the latest announcements.',game:'GTA_6',category:'RELEASE_DATE'},
};
export function guidePath(kind:string,slug:string){return kind==='HEIST'?`/gta-online/heists/${slug}`:kind==='CHARACTER'?`/gta-6/characters/${slug}`:kind==='LOCATION'?`/gta-6/locations/${slug}`:kind==='TRAILER'?`/gta-6/trailers/${slug}`:`/guides/${slug}`;}
