import { emptyWeekly, type Entity } from './validation';
export type Field = { name: string; label: string; type?: 'text' | 'textarea' | 'json' | 'url' | 'number' | 'checkbox' | 'datetime-local'; required?: boolean; options?: string[]; hint?: string; default?: string | number | boolean; wide?: boolean; min?: number; max?: number };
const game = { name: 'game', label: 'Game', options: ['GTA_ONLINE', 'GTA_6', 'GTA_5', 'ROCKSTAR'] };
const state = { name: 'status', label: 'Editorial status', options: ['DRAFT', 'REVIEW', 'PUBLISHED', 'ARCHIVED'] };
const verify = { name: 'verification_status', label: 'Verification', options: ['UNKNOWN', 'CONFIRMED', 'REPORTED', 'RUMOR'] };
const slug: Field = { name: 'slug', label: 'URL slug', required: true, hint: 'Lowercase words separated by hyphens.' };
const source: Field = { name: 'source_url', label: 'Evidence / source URL', type: 'url', hint: 'HTTPS. Confirmed evidence requires an enabled official source. Attributed reporting must match its configured source.' };
const verified: Field = { name: 'verified_at', label: 'Evidence verified at (UTC)', type: 'datetime-local' };
const image: Field = { name: 'image', label: 'Image URL', type: 'url' };
const confidence: Field = { name: 'confidence_score', label: 'Evidence confidence (0–100)', type: 'number', default: 0, min: 0, max: 100, hint: 'Record your confidence in the sourced gameplay facts.' };
export const fields: Record<Entity, Field[]> = {
  articles: [
    { name: 'title', label: 'Headline', required: true, wide: true }, slug, game, { name: 'category', label: 'Category', default: 'News', required: true }, state, verify,
    { name: 'excerpt', label: 'Excerpt', type: 'textarea', wide: true, required: true }, { name: 'content', label: 'Story content', type: 'textarea', wide: true, required: true, hint: 'Plain text / Markdown. HTML is displayed as text in the private preview.' },
    { ...source, required: true }, { name: 'source_name', label: 'Source name', required: true }, { name: 'confidence_score', label: 'Evidence confidence (0–100)', type: 'number', default: 0 },
    { name: 'featured_image', label: 'Featured image URL', type: 'url' }, { name: 'image_alt', label: 'Image description' },
    { name: 'seo_title', label: 'SEO title', hint: 'Up to 70 characters; leave blank to use the headline.' }, { name: 'seo_description', label: 'SEO description', type: 'textarea', hint: 'Up to 180 characters; leave blank to use the excerpt.' },
    { name: 'keywords', label: 'Keywords', type: 'json', default: '[]', hint: 'JSON array of strings, e.g. ["weekly update"].' }, { name: 'entities', label: 'Entities', type: 'json', default: '[]', hint: 'JSON array of game, character, or vehicle names.' },
    { name: 'featured', label: 'Feature on the homepage', type: 'checkbox' }, { name: 'trending', label: 'Mark as trending', type: 'checkbox' }, { name: 'breaking', label: 'Breaking news', type: 'checkbox' }, { name: 'breaking_expires_at', label: 'Breaking expiry (UTC)', type: 'datetime-local' },
  ],
  weekly: [slug, state, verify, { name: 'event_start', label: 'Event start (UTC)', type: 'datetime-local', required: true }, { name: 'event_end', label: 'Exclusive event end (UTC)', type: 'datetime-local', required: true, hint: 'The update stops being active at this instant. Maximum event window: 21 days.' }, { name: 'last_checked_at', label: 'Source last checked (UTC)', type: 'datetime-local', required: true }, { ...source, required: true }, { name: 'article_id', label: 'Related article ID', required: true, hint: 'Required article UUID. Copy it from the related article editor URL.' }, { name: 'data', label: 'Weekly update details', type: 'json', default: JSON.stringify(emptyWeekly, null, 2), wide: true, hint: 'All keys are required. Bonuses use activity, moneyMultiplier, rpMultiplier; discounts use name and discount. Multipliers are numbers or null. Other collections contain strings.' }],
  vehicles: [ { name: 'name', label: 'Vehicle name', required: true }, slug, { name: 'vehicle_class', label: 'Vehicle class', required: true }, { name: 'price', label: 'Price (GTA$)', type: 'number' }, { name: 'top_speed', label: 'Top speed (mph)', type: 'number' }, { name: 'retailer', label: 'Retailer' }, { name: 'seats', label: 'Seats', type: 'number' }, image, { name: 'description', label: 'Description', type: 'textarea', required: true, wide: true }, source, verified, confidence, { name: 'added_at', label: 'Added to game (UTC)', type: 'datetime-local' }, { name: 'features', label: 'Features', type: 'json', default: '[]', wide: true, hint: 'JSON array of strings.' } ],
  guides: [{ name: 'title', label: 'Title', required: true }, slug, { name: 'kind', label: 'Guide type', options: ['GUIDE', 'HEIST', 'CHARACTER', 'LOCATION', 'TRAILER', 'FEATURE'] }, game, verify, image, { name: 'description', label: 'Description', type: 'textarea', required: true, wide: true }, { name: 'content', label: 'Content', type: 'textarea', required: true, wide: true }, { name: 'facts', label: 'Structured facts', type: 'json', default: '{}', wide: true, hint: 'JSON object with string keys and values, e.g. {"Location":"Los Santos"}.' }, source, verified, confidence],
  sources: [{ name: 'name', label: 'Source name', required: true }, { name: 'url', label: 'Feed / endpoint URL', type: 'url', required: true }, { name: 'source_type', label: 'Adapter', options: ['RSS', 'JSON', 'HTML', 'YOUTUBE', 'COMMUNITY'] }, { name: 'trust_level', label: 'Trust level', options: ['UNVERIFIED', 'COMMUNITY', 'TRUSTED_MEDIA', 'OFFICIAL'], hint: 'Official trust is reserved for approved Rockstar-owned hosts.' }, { name: 'category', label: 'Category', default: 'News', required: true }, { name: 'fetch_frequency', label: 'Fetch every (minutes)', type: 'number', default: 60, hint: '5–10,080 minutes.' }, { name: 'allowed_hosts', label: 'Allowed fetch hosts', type: 'json', default: '[]', wide: true, hint: 'Exact DNS hostnames as a JSON array. Include the feed hostname. No wildcards or private addresses.' }, { name: 'enabled', label: 'Enable ingestion', type: 'checkbox', default: false }, { name: 'allow_html', label: 'Permit HTML fetching', type: 'checkbox', default: false }],
  settings: [{ name: 'site_name', label: 'Publication name', default: 'Los Santos Wire', required: true }, { name: 'release_date', label: 'Verified GTA VI release date (UTC)', type: 'datetime-local', hint: 'Only enter dates confirmed by Rockstar. Clear all release fields to withdraw.' }, { name: 'release_source_url', label: 'Official release announcement URL', type: 'url' }, { name: 'release_verified_at', label: 'Announcement verified at (UTC)', type: 'datetime-local' }, { name: 'confidence_threshold', label: 'Minimum publication confidence (0–100)', type: 'number', default: 85 }, { name: 'auto_publish_official', label: 'Automatically publish verified official reporting', type: 'checkbox', default: false }, { name: 'auto_publish_trusted', label: 'Automatically publish trusted reporting meeting policy', type: 'checkbox', default: false }, { name: 'auto_publish_community', label: 'Automatically publish attributed community reporting', type: 'checkbox', default: false, hint: 'Remains REPORTED. Rumors, conflicting evidence, and low-confidence claims are held for review by the pipeline.' }],
};
